version: "3.8"

services:
  kafka:
    image: bitnami/kafka
    container_name: kafka
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_LISTENERS: "CONTROLLER://:9093,PLAINTEXT://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9092" ]
      interval: 5s
      timeout: 10s
      retries: 6
      start_period: 15s
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka
  crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_TOPIC: "stackoverflow_questions"
      SCRAPE_INTERVAL: "60" # Seconds between scrapes
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./StackOverFlow_Crawler_Kafka:/app/StackOverFlow_Crawler_Kafka

volumes:
  kafka_data:
    driver: local
